theme: minima
title: Eider
author: eidergomez
email: eider.gomez@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Realizar un "blog" para aprender qué es github.

# social links
twitter_username: tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username: eidergomezithub # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principa
