title: Portafolio
author: eidergomez
email: eider.gomez@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
 mi sitio web es el mejor.

# social links
#twitter_username: tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  eidergomez # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal