<<<<<<< HEAD
title: Repositorio de Eider
author: eidergomez
email: eider.gomez@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
 Este es mi sitio web, podras encontrar contenido relacionado con la web. Espero que te encante.

# social links
#twitter_username: # tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  eidergomez # NO incluyas el carácter @ character, ¡o la compilación fallará!
=======
theme: minima
title: Eider
author: eidergomez
email: eider.gomez@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Esto es un blog con relacion a contenido web.

# social links
twitter_username: # tu-usuario-twitter # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username: eidergomezithub # NO incluyas el carácter @ character, ¡o la compilación fallará!
>>>>>>> 8d96b8f0ae4672171a23306c935f5e575fa80fe9

show_excerpts: false 
